spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/wangtong213/open-office-platfrom.git
          username: 1165308717@qq.com
          password: .0..0.
          search-paths: config
  application:
    name: ch12-1-config-server-placeholders
server:
    port: 9090
logging:
  level:
    root: debug
